### ISSUE TITLE
Link in repo summary seems to be down

### ISSUE THREAD

**Issue by razzeee** [mgold/elm-animation#10]

**Comment by mgold** [comment]
Will update with package docs link once 0.19 version is released.

**Comment by w0rm** [comment]
@mgold by the way, if you want to link to working examples from the docs, they can be published to github pages, I've written the following script for elm-physics: https://github.com/w0rm/elm-physics/blob/master/gh-pages.sh

**Comment by mgold** [comment]
I was going to use Ellie but thanks.

**Comment by mgold** [comment]
Fixed.
