### ISSUE TITLE
Could not find module 'Animation': 'animation.elm' file should start with a capital?

### ISSUE THREAD

**Issue by lihop** [mgold/elm-animation#2]
I get this error when trying to compile an elm file that imports Animation, both when using elm-reactor and elm-make:

```
Error when searching for modules exposed by elm-package.json:
    Could not find module 'Animation'

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json
```

If I go deep down into the elm-stuff directory:

```
elm-stuff/packages/mgold/elm-animation/1.0.1/
```

and rename `animation.elm` to `Animation.elm`, then everything compiles fine.
Maybe the the file name should start with a capital to prevent this error?
# 

**Extra info:**

Installed the usual way:

```
elm-package install mgold/elm-animation
```

Using elm-make version 0.2 and elm-reactor version 0.3.2.

**Comment by mgold** [comment]
You appear to be using an old version of Elm. Try upgrading to 0.16, which should fix your issue.

That said, I think you are correct that files containing modules should be capitalized.

**Comment by pisys** [comment]
Got the same problem. Using elm-make 0.16 (Elm Platform 0.16) on an Ubuntu box.

**Comment by mgold** [comment]
I bet it's because Mac does weird things with filename case sensitivity. I'll push out a patch release later today.

**Comment by mgold** [comment]
Version 1.0.3 is released. Please verify the fix.

**Comment by mgold** [comment]
@lihop and @Pisys, does 1.0.3 resolve the issue?

**Comment by lihop** [comment]
@mgold Thanks for the fix. I upgraded to 0.16 and can confirm 1.0.3 resolves the issue.

**Comment by pisys** [comment]
Thanks too! 1.0.3 works for me also.
