### ISSUE TITLE
Get current animation position

### ISSUE THREAD

**Issue by sdoomz** [mgold/elm-animation#4]
Hi! I'am trying to implement simple jump animation with elm-animation package.
I have initial fall down animation: 

``` elm
type alias Model =
    { r : Float, x : Float, y : Animation, w : Int, h : Int, clock : Time }
model0 =
    Model 30
        0
        (animation 0 |> from 200 |> to -200 |> duration Time.second |> delay Time.second)
        0
        0
        0
```

and by clicking mouse button I want to retarget model up.
Here is my ‘Jump’ handler for ‘Update’ block: 

``` elm
Jump { x } ->
  let    
    y = retarget model.clock (currentPosition + 50) model.y
  in
    { model | y = y }
```

Any ideas how to get ‘currentPosition’ or retarget animation up in correct way?

**Comment by mgold** [comment]
`currentPosition = animate model.clock model.y`?

**Comment by sdoomz** [comment]
Yeah, it is exact what I am looking for. Thx
