### ISSUE TITLE
animating the height of a div so that it fits the content

### ISSUE THREAD

**Issue by eniac314** [mgold/elm-animation#7]
I am using mgold/elm-animation to animate the height of a div. I would like to be able to transition between 0 and a height that fits the content of my div (the equivalent in css of height: auto;)

I have found a Jquery solution here that uses $(this).css("height","auto").height(); to get the correct height to transition to.

Can I do that with this library?

**Comment by mgold** [comment]
No, you this library doesn't know anything about the DOM and won't be able to know the automatically derived height in pixels.

But, maybe you could interpolate from 0 to 100 and set the height as a percentage?

**Comment by eniac314** [comment]
I thought about it but the height in percent would be dependent on the
containing element's height, not on it's content, and I need the content to
determine the height.

Basically I want to do something like google's "People also ask" widget


​

http://jsfiddle.net/UezUj/1/

but in elm.

**Comment by mgold** [comment]
Not sure. You can ask in the #animations channel on [Slack](http://elmlang.herokuapp.com/).
