### ISSUE TITLE
Upgrade to 0.19

### ISSUE THREAD

**Issue by w0rm** [mgold/elm-animation#8]
Hi, I've noticed a part of work is already done in the 0.19 branch, do you need any help with porting the examples?

**Comment by mgold** [comment]
Help porting the examples would be great.

I thought I had introduced a weird bug when I was updating the README, and decided some unit tests would be in order, but that I didn't have time for it that night.

I just poked at it again and found that my setup was incorrect and everything is working.

I want to stop having the same documentation in the README and in the module, and I still want to write those tests. If you help out with the examples -- which I don't think were even ported to 0.18 -- then I think it should only take a day or two.

**Comment by mgold** [comment]
I've added you as a collaborator - go ahead and branch from `0.19`.

**Comment by w0rm** [comment]
@mgold thanks! I will upgrade the examples on the weekend.

**Comment by w0rm** [comment]
@mgold are you sure about using `Posix` for the animation start time? The examples rely on `AnimationFrame.diffs` [that has become a `Float` now](https://package.elm-lang.org/packages/elm/browser/latest/Browser-Events#onAnimationFrameDelta). So I would still have to store `Time` as `Float` in the model, and convert it to `Posix` in order to use `Animation` api.

**Comment by mgold** [comment]
I independently thought better of it and pushed a new commit that gets rid of it.

**Comment by mgold** [comment]
To be clear, I think we should use `onAnimationFrameDelta` and not `onAnimationFrame`.

**Comment by mgold** [comment]
I'm with family this weekend so I might not get a chance to rework the README and stuff for another few days.

**Comment by w0rm** [comment]
@mgold there is no rush, enjoy your weekend!

**Comment by mgold** [comment]
2.0.0 is published!

**Comment by w0rm** [comment]
@mgold awesome! Thank you!
